### ISSUE TITLE
About args.wtvfile in prototypes.py

### ISSUE THREAD

**Issue by whobefore** [psmmettes/hpn#1]
Hi. If I want to use the wtvfile, where can I get it? Thanks a lot!

**Comment by Melinda315** [comment]
Hi, I'd like to ask you about the version about python, torch and torchvision. Could you tell me about the details?

**Comment by psmmettes** [comment]
Hi whobefore,

Thanks for pointing this out. I will add links to the wtvfiles for the datasets used in the paper in the README.
